DELETE from students;  
insert into students values (null, 'Addison George', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Mark Pitts', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Nala Cook', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Ezekiel Robbins', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Stevie Mack', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Esteban Goodman', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Carolina Vasquez', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Rowan Parrish', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Tiana Moran', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Tate Landry', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Brynleigh Stanley', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Manuel Wilkinson', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Siena Watson', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Greyson Lugo', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Kaylie Blackwell', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Marcellus Carpenter', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Lilly Quintero', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Thatcher Oliver', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Camille Valenzuela', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Jamari Gallegos', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Ari Wilkinson', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Leonard Gallegos', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Ari Larsen', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Brycen McIntyre', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Rebekah Leal', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Cedric Zavala', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Liv Wiley', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Mathew Leon', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Amora Flynn', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Kannon Baker', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Isla Kirby', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Tony McPherson', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Emmaline French', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Corey Sherman', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Addilyn Wilcox', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Jerry Roberson', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Sasha McDowell', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Lachlan Fox', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Juliette Humphrey', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Krew Reyna', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Luella Stevens', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Zachary Lucero', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Ila Ellis', 'test@pengroup.com', '1990-01-01', datetime(), null, null);
insert into students values (null, 'Cole Odom', 'test@pengroup.com', '1990-01-01', datetime(), null, null);

delete from courses;
insert into courses values (null, 'Chinese','2024-06-01','2024-09-30',datetime(), null, null);
insert into courses values (null, 'English','2024-06-01','2024-09-30',datetime(), null, null);
insert into courses values (null, 'French','2024-06-01','2024-09-30',datetime(), null, null);
insert into courses values (null, 'Japanese','2024-06-01','2024-09-30',datetime(), null, null);
insert into courses values (null, 'Spainsh','2024-06-01','2024-09-30',datetime(), null, null);

delete from student_enrolment;
insert into student_enrolment values (null, (select id from students where name = 'Addison George'), (select id from courses where name = 'Chinese') , datetime(), datetime());
insert into student_enrolment values (null, (select id from students where name = 'Addison George'), (select id from courses where name = 'English'), datetime(), datetime());
insert into student_enrolment values (null, (select id from students where name = 'Addison George'), (select id from courses where name = 'French'), datetime(), datetime());
insert into student_enrolment values (null, (select id from students where name = 'Addison George'), (select id from courses where name = 'Japanese'), datetime(), datetime());
insert into student_enrolment values (null, (select id from students where name = 'Addison George'), (select id from courses where name = 'Spainsh'), datetime(), datetime());

insert into student_enrolment values (null, (select id from students where name = 'Mark Pitts'), (select id from courses where name = 'Chinese'), datetime(), datetime());
insert into student_enrolment values (null, (select id from students where name = 'Nala Cook'), (select id from courses where name = 'Chinese'), datetime(), datetime());
insert into student_enrolment values (null, (select id from students where name = 'Ezekiel Robbins'), (select id from courses where name = 'Chinese'), datetime(), datetime());
insert into student_enrolment values (null, (select id from students where name = 'Stevie Mack'), (select id from courses where name = 'Chinese'), datetime(), datetime());